---
# Variables used by Vagrantfile are defined here

servers:
  - name: allinone
    box: quarkslab/debian-8.6.0-amd64
    ip: 172.16.1.30
    hostname: brain.irma
    aliases:
      - irma-allinone.local
      - api.irma-allinone.local

    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
    share_code: false
##   - name: probe-win
##     box: eval-win10-enterprise
##     ip: 172.16.1.31
##     hostname: probe-win.irma
##     cpus: 2
##     cpuexecutioncap: 100
##     memory: 2048
##     windows: true

libvirt_config:
  driver: kvm
  # connect_via_ssh: true
  # host:
  # username:
  # storage_pool_name:
  # id_ssh_key_file:

ansible_config:
  extra_vars:
    vagrant: true
  groups:
    web-ui:
      - allinone
    frontend:
      - allinone
    brain:
      - allinone
    clamav:
      - allinone
    comodo:
      - allinone
    mcafee:
      - allinone
    trid:
      - allinone
    static-analyzer:
      - allinone
    virustotal:
      - allinone
    windows-probe:
      - probe-win
    "probe:children":
      - clamav
      - comodo
      - mcafee
      - trid
      - static-analyzer
      - virustotal
      - windows-probe
    "windows:children":
      - windows-probe
